version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: matheus
      POSTGRES_PASSWORD: matheus
      POSTGRES_DB: temperatura-musical
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  springboot-app:
    image: mathgunz16/temperatura-musical:1.0.0
    container_name: temperatura_musical
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/temperatura-musical
      SPRING_DATASOURCE_USERNAME: matheus
      SPRING_DATASOURCE_PASSWORD: matheus
    ports:
      - "80:8080"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge